exclude_paths:
  - '.cicd/**'
  - '.circleci/**'
  - 'docs/**'
  - '**/*.md'
  - '.*'
  - '*.md'
  - '*.ps1'
  - '*.sh'
  - 'CODEOWNERS'
  - 'tests/**'
  - '.vscode/**'
duplication:
  exclude_paths:
    - tests/*